# マップ情報
map_information = [

  # マージ教会の領域
  {
    "map_id":619,
    "map_name":"マージ教会の領域",
    "area_name":"マージ教会の領域",
    "parent_map_id":-1,
    "unused":true
  },

  # イシュトールの海岸洞窟
  {
    "map_id":374,
    "map_name":"イシュトールの海岸洞窟",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":true
  },
  {
    "map_id":256,
    "map_name":"海岸洞窟１",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":662,
    "map_name":"隠し部屋",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":256,
    "unused":true
  },
  {
    "map_id":369,
    "map_name":"海岸洞窟２",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":006,
    "map_name":"海岸巫女の住処",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":369,
    "unused":true
  },
  {
    "map_id":499,
    "map_name":"隠し部屋",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":369,
    "unused":true
  },
  {
    "map_id":370,
    "map_name":"海岸洞窟３",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":004,
    "map_name":"海岸巫女の住処",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":370,
    "unused":true
  },
  {
    "map_id":037,
    "map_name":"隠し部屋",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":370,
    "unused":true
  },
  {
    "map_id":371,
    "map_name":"海岸洞窟４",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":372,
    "map_name":"海岸洞窟５",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":002,
    "map_name":"海岸巫女の住処",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":372,
    "unused":true
  },
  {
    "map_id":023,
    "map_name":"隠し通路",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":372,
    "unused":true
  },
  {
    "map_id":373,
    "map_name":"海岸洞窟６",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":375,
    "map_name":"海岸洞窟の隠し",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":373,
    "unused":true
  },
  {
    "map_id":530,
    "map_name":"隠し部屋",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":375,
    "unused":true
  },
  {
    "map_id":111,
    "map_name":"セドリックの祠",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":375,
    "unused":true
  },
  {
    "map_id":255,
    "map_name":"海岸１",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":431,
    "map_name":"海岸２",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":036,
    "map_name":"海岸巫女の隠し倉庫",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":431,
    "unused":true
  },
  {
    "map_id":257,
    "map_name":"隠れ岬 入口",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":664,
    "map_name":"隠し部屋",
    "area_name":"イシュトールの海岸洞窟",
    "parent_map_id":257,
    "unused":true
  },

  # カザッフの沈没船
  {
    "map_id":258,
    "map_name":"カザッフの沈没船",
    "area_name":"カザッフの沈没船",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":259,
    "map_name":"沈没船の倉庫",
    "area_name":"カザッフの沈没船",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":260,
    "map_name":"沈没船の甲板",
    "area_name":"カザッフの沈没船",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":588,
    "map_name":"船長室",
    "area_name":"カザッフの沈没船",
    "parent_map_id":260,
    "unused":true
  },
  {
    "map_id":589,
    "map_name":"前甲板",
    "area_name":"カザッフの沈没船",
    "parent_map_id":260,
    "unused":true
  },
  {
    "map_id":261,
    "map_name":"隠れ岬",
    "area_name":"カザッフの沈没船",
    "parent_map_id":-1,
    "unused":false
  },

  # 海底トンネル
  {
    "map_id":206,
    "map_name":"海底トンネル",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":true
  },
  {
    "map_id":205,
    "map_name":"海底トンネル 入口",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":340,
    "map_name":"海底トンネル１",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":341,
    "map_name":"海底トンネル結界",
    "area_name":"海底トンネル",
    "parent_map_id":340,
    "unused":true
  },
  {
    "map_id":522,
    "map_name":"海底トンネル:結界-A接続",
    "area_name":"海底トンネル",
    "parent_map_id":341,
    "unused":true
  },
  {
    "map_id":342,
    "map_name":"海底トンネル２：分岐",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":343,
    "map_name":"海底トンネル：落とし",
    "area_name":"海底トンネル",
    "parent_map_id":342,
    "unused":true
  },
  {
    "map_id":344,
    "map_name":"更に地下",
    "area_name":"海底トンネル",
    "parent_map_id":343,
    "unused":true
  },
  {
    "map_id":348,
    "map_name":"ルートA",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":true
  },
  {
    "map_id":345,
    "map_name":"海底トンネル:A-1",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":346,
    "map_name":"海底トンネル:A-2",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":347,
    "map_name":"海底トンネル:A-3",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":349,
    "map_name":"隠し",
    "area_name":"海底トンネル",
    "parent_map_id":347,
    "unused":false
  },
  {
    "map_id":350,
    "map_name":"海底トンネル:A-4",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":876,
    "map_name":"隠し",
    "area_name":"海底トンネル",
    "parent_map_id":350,
    "unused":false
  },
  {
    "map_id":351,
    "map_name":"海底トンネル:A-5 山接続",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":428,
    "map_name":"海底トンネル：連絡",
    "area_name":"海底トンネル",
    "parent_map_id":351,
    "unused":false
  },
  {
    "map_id":429,
    "map_name":"海底トンネル：山へ",
    "area_name":"海底トンネル",
    "parent_map_id":351,
    "unused":false
  },
  {
    "map_id":352,
    "map_name":"海底トンネル:C-1",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":353,
    "map_name":"海底トンネル:C-2(結界)",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":354,
    "map_name":"海底トンネル:C-3",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":355,
    "map_name":"隠し",
    "area_name":"海底トンネル",
    "parent_map_id":354,
    "unused":false
  },
  {
    "map_id":357,
    "map_name":"海底トンネル:D-1(クレスト)",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":356,
    "map_name":"海底トンネル:D-2",
    "area_name":"海底トンネル",
    "parent_map_id":348,
    "unused":false
  },
  {
    "map_id":358,
    "map_name":"ルートB",
    "area_name":"海底トンネル",
    "parent_map_id":-1,
    "unused":true
  },
  {
    "map_id":359,
    "map_name":"海底トンネル:B-1",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":360,
    "map_name":"海底トンネル:B-2",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":361,
    "map_name":"海底トンネル:B-3",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":608,
    "map_name":"隠し部屋",
    "area_name":"海底トンネル",
    "parent_map_id":361,
    "unused":false
  },
  {
    "map_id":362,
    "map_name":"海底トンネル:B-4",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":363,
    "map_name":"海底トンネル:B-5(D接続)",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":364,
    "map_name":"海底トンネル:B-6(古書接続)",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":365,
    "map_name":"海底トンネル:E-1",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":367,
    "map_name":"隠し",
    "area_name":"海底トンネル",
    "parent_map_id":365,
    "unused":false
  },
  {
    "map_id":366,
    "map_name":"海底トンネル:E-2",
    "area_name":"海底トンネル",
    "parent_map_id":358,
    "unused":false
  },
  {
    "map_id":339,
    "map_name":"隠し部屋",
    "area_name":"海底トンネル",
    "parent_map_id":366,
    "unused":false
  },

  # ブリューサの古書院
  {
    "map_id":402,
    "map_name":"ブリューサの古書院",
    "area_name":"ブリューサの古書院",
    "parent_map_id":-1,
    "unused":true
  },
  {
    "map_id":404,
    "map_name":"図書館：左側",
    "area_name":"ブリューサの古書院",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":403,
    "map_name":"海底トンネル接続",
    "area_name":"ブリューサの古書院",
    "parent_map_id":404,
    "unused":false
  },
  {
    "map_id":215,
    "map_name":"結界部屋",
    "area_name":"ブリューサの古書院",
    "parent_map_id":404,
    "unused":false
  },
  {
    "map_id":405,
    "map_name":"書庫",
    "area_name":"ブリューサの古書院",
    "parent_map_id":404,
    "unused":false
  },
  {
    "map_id":607,
    "map_name":"隠し部屋",
    "area_name":"ブリューサの古書院",
    "parent_map_id":405,
    "unused":false
  },
  {
    "map_id":506,
    "map_name":"図書館",
    "area_name":"ブリューサの古書院",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":413,
    "map_name":"中央閲覧室：中央１階",
    "area_name":"ブリューサの古書院",
    "parent_map_id":506,
    "unused":false
  },
  {
    "map_id":610,
    "map_name":"地下１階",
    "area_name":"ブリューサの古書院",
    "parent_map_id":413,
    "unused":false
  },
  {
    "map_id":193,
    "map_name":"中央２階",
    "area_name":"ブリューサの古書院",
    "parent_map_id":506,
    "unused":false
  },
  {
    "map_id":612,
    "map_name":"図書館２階右",
    "area_name":"ブリューサの古書院",
    "parent_map_id":193,
    "unused":false
  },
  {
    "map_id":613,
    "map_name":"図書館２階左",
    "area_name":"ブリューサの古書院",
    "parent_map_id":193,
    "unused":false
  },
  {
    "map_id":670,
    "map_name":"隠し書庫",
    "area_name":"ブリューサの古書院",
    "parent_map_id":193,
    "unused":false
  },
  {
    "map_id":432,
    "map_name":"中央３階",
    "area_name":"ブリューサの古書院",
    "parent_map_id":506,
    "unused":false
  },
  {
    "map_id":614,
    "map_name":"図書館３階左",
    "area_name":"ブリューサの古書院",
    "parent_map_id":432,
    "unused":false
  },
  {
    "map_id":615,
    "map_name":"図書館３階右",
    "area_name":"ブリューサの古書院",
    "parent_map_id":432,
    "unused":false
  },
  {
    "map_id":616,
    "map_name":"中央４階",
    "area_name":"ブリューサの古書院",
    "parent_map_id":506,
    "unused":false
  },
  {
    "map_id":617,
    "map_name":"図書館４階右",
    "area_name":"ブリューサの古書院",
    "parent_map_id":616,
    "unused":false
  },
  {
    "map_id":624,
    "map_name":"図書館４階左",
    "area_name":"ブリューサの古書院",
    "parent_map_id":616,
    "unused":false
  },
  {
    "map_id":668,
    "map_name":"隠されたテラス",
    "area_name":"ブリューサの古書院",
    "parent_map_id":624,
    "unused":false
  },
  {
    "map_id":577,
    "map_name":"秘蔵庫",
    "area_name":"ブリューサの古書院",
    "parent_map_id":506,
    "unused":false
  },
  {
    "map_id":533,
    "map_name":"図書館：右側",
    "area_name":"ブリューサの古書院",
    "parent_map_id":-1,
    "unused":false
  },
  {
    "map_id":534,
    "map_name":"書庫",
    "area_name":"ブリューサの古書院",
    "parent_map_id":533,
    "unused":false
  },

  # 古代の遺跡
  {
    "map_id":,
    "map_name":"",
    "area_name":"古代の遺跡",
    "parent_map_id":-1,
    "unused":false
  },


  # 未使用マップ
  {
    "map_id":,
    "map_name":"",
    "area_name":"ブリューサの古書院",
    "parent_map_id":-1,
    "unused":false
  },

]